function pesquisaBinaria  (list, item)  {
  let baixo = 0;
  let alto = list.length - 1;

  while (baixo <= alto) {
    const meio = Math.floor((baixo + alto) / 2);
    const chute = list[meio];

    if (chute === item) {
      return meio;
    } else if (chute > item) {
      alto = meio - 1;
    } else {
      baixo = meio + 1;
    }
    
    console.log('chute',chute )
  }
  return null;
};

const lista = [
  "ZANITY",
  "NETERIA",
  "KLUGGER",
  "EDECINE",
  "COMVEYER",
  "REMOLD",
  "PRIMORDIA",
  "DADABASE",
  "ASIMILINE",
  "OCTOCORE",
  "IMANT",
  "INSECTUS",
  "PRINTSPAN",
  "BALOOBA",
  "KINETICA",
  "BUZZMAKER",
  "FUELWORKS",
  "IDEALIS",
  "IPLAX",
  "OTHERSIDE",
  "INRT",
  "CUJO",
  "LUNCHPOD",
  "PROGENEX",
  "LUMBREX",
  "COMTEXT",
  "TURNLING",
  "ELENTRIX",
  "INTERLOO",
  "QUALITEX",
  "VETRON",
  "SIGNIDYNE",
  "GADTRON",
  "ANIXANG",
  "ENTROPIX",
  "ERSUM",
  "EXOPLODE",
  "OCEANICA",
  "ZOLAREX",
  "ELEMANTRA",
  "ECLIPTO",
  "OVERPLEX",
  "ISOSWITCH",
  "MONDICIL",
  "EXOSPEED",
  "ZILLACTIC",
  "NETROPIC",
  "LIMOZEN",
  "MIXERS",
  "ASSURITY",
  "SENMEI",
  "STREZZO",
  "SONGLINES",
  "ISOSTREAM",
  "OLUCORE",
  "QUOTEZART",
  "DOGNOST",
  "HAIRPORT",
  "ZOXY",
  "MEDESIGN",
  "BLURRYBUS",
  "ASSISTIA",
  "MEGALL",
  "PHOTOBIN",
  "ZANILLA",
  "ACRODANCE",
  "CENTREXIN",
  "COMBOGENE",
  "MIRACULA",
  "MEDALERT",
  "PODUNK",
  "HELIXO",
  "RETRACK",
  "GENMEX",
  "MAXIMIND",
  "VIDTO",
  "VINCH",
  "MALATHION",
  "ZAPPIX",
  "ARTIQ",
  "ELECTONIC",
  "AVENETRO",
  "HYPLEX",
  "MOREGANIC",
  "AUTOGRATE",
  "CENTREE",
  "EXOBLUE",
  "HIVEDOM",
  "HAWKSTER",
  "EARTHMARK",
  "GLUKGLUK",
  "SIGNITY",
  "KOG",
  "VOLAX",
  "SNACKTION",
  "ANDERSHUN",
  "NORALI",
  "AQUAMATE",
  "DANCERITY",
  "ACUMENTOR",
  "ROCKYARD",
  "DATACATOR",
  "SNIPS",
  "OLYMPIX",
  "TECHTRIX",
  "ORBIFLEX",
  "EZENT",
  "SUSTENZA",
  "FARMEX",
  "GROK",
  "MENBRAIN",
  "DIGIRANG",
  "VIRVA",
  "HATOLOGY",
  "KOFFEE",
  "SOFTMICRO",
  "SENTIA",
  "RODEMCO",
  "IRACK",
  "NEWCUBE",
  "AQUOAVO",
  "VELITY",
  "ZILLIDIUM",
  "VENDBLEND",
  "EXTRO",
  "TETRATREX",
  "ROCKLOGIC",
  "GENMOM"
];

console.log(pesquisaBinaria(lista, "VELITY"))
